### PR TITLE
`@master` -> `@v1`

### PR DESCRIPTION
**Pull request by mxcl**
There is no `@master`.

### CODE REVIEW

**Comment by mxcl** [comment]
k well the `v1` tag is broken.

I suggest an action like @fischerscode/tagger for keeping these in sync.

**Comment by mxcl** [comment]
k well, maybe it’s not ready for use?

https://github.com/pkgxsh/www/actions/runs/5841707111/job/15842132648

**Comment by vladcos** [comment]
@mxcl thx for the fix, apologies, been on a summer break

as to https://github.com/pkgxsh/www/actions/runs/5841707111/job/15842132648
`sfargs` is not a valid input, should be `s3args`

also `target` should end with a slash
` target: s3://***/`

**Comment by mxcl** [comment]
Thanks for the help!

**Pull request merged**
